// experience costs for each skill level
let skillExperienceCosts = [
  160, 480, 960, 1600, 2400, 3360, 4480, 5760, 7200, 8800, 10576, 12544, 14720, 17120, 19760, 22656,
  25841, 29350, 33220, 37490, 42201, 47396, 53120, 59420, 66345, 73270, 80195, 87120, 94045, 101870,
  109695, 117520, 125345, 133170, 142220, 151270, 160320, 169370, 178420, 189070, 199720, 210370,
  221020, 231670, 244345, 257020, 269695, 282370, 295045, 310220,
];

const skillCap = skillExperienceCosts.length;

const creatureAttributes = [
  {
    id: 0,
    primary: "Strength",
    primaryAlt: "Str",
    secondary: "Might",
    primaryDesc: "Governs all Strength skills.",
    secondaryDesc: "Physical power",
  },
  {
    id: 1,
    primary: "Endurance",
    primaryAlt: "End",
    secondary: "Finesse",
    primaryDesc: "Governs all Endurance skills.",
    secondaryDesc: "Physical plasticity",
  },
  {
    id: 2,
    primary: "Intellect",
    primaryAlt: "Int",
    secondary: "Cunning",
    primaryDesc: "Governs all Intellect skills.",
    secondaryDesc: "Mental power",
  },
  {
    id: 3,
    primary: "Intuition",
    primaryAlt: "Tui",
    secondary: "Instinct",
    primaryDesc: "Governs all Intuition skills.",
    secondaryDesc: "Mental plasticity",
  },
  {
    id: 4,
    primary: "Aptitude",
    primaryAlt: "Apt",
    secondary: null,
    primaryDesc: "Governs all tradeskills.",
    secondaryDesc: null,
  },
];

const creatureSkills = [
  {
    id: 0,
    name: "Heavy Weapons",
    type: "Combat",
    formulaic: "+1 point per [STR] / 2",
    desc: "None.",

    specStatus: 0,
  },
  {
    id: 1,
    name: "Life Chanting",
    type: "Combat",
    formulaic: "+1 point per [TUI] / 2",
    desc: "The commanding of life through magical chants. Heal, harm, and infuse creatures with powerful vitality chants.",
    specStatus: 2,
  },
  {
    id: 2,
    name: "Light Weapons",
    type: "Combat",
    formulaic: "+1 point per [END] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 3,
    name: "Missile Weapons",
    type: "Combat",
    formulaic: "+1 point per [END] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 4,
    name: "War Chanting",
    type: "Combat",
    formulaic: "+1 point per [INT] / 2",
    desc: "None.",
    specStatus: 3,
  },
  {
    id: 5,
    name: "Evasive Tactics",
    type: "Mitigation",
    formulaic: "+1 point per [END + STR] / 4",
    desc: "None.",
    specStatus: 1,
  },
  {
    id: 6,
    name: "Resilience",
    type: "Mitigation",
    formulaic: "+1 point per [STR + END] / 4",
    desc: "None.",
    specStatus: 1,
  },
  {
    id: 7,
    name: "Warding",
    type: "Mitigation",
    formulaic: "+1 point per [INT + TUI] / 4",
    desc: "None.",
    specStatus: 2,
  },
  {
    id: 8,
    name: "Alchemy",
    type: "Trade",
    formulaic: "+1 point per [INT + APT] / 4",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 9,
    name: "Armorsmith",
    type: "Trade",
    formulaic: "+1 point per [STR + APT] / 4",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 10,
    name: "Bowyer",
    type: "Trade",
    formulaic: "+1 point per [END + APT] / 4",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 11,
    name: "Jeweler",
    type: "Trade",
    formulaic: "+1 point per [TUI + APT] / 4",
    desc: "None.",
    specStatus: 2,
  },
  {
    id: 12,
    name: "Leatherworking",
    type: "Trade",
    formulaic: "+1 point per [END + APT] / 4",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 13,
    name: "Tailoring",
    type: "Trade",
    formulaic: "+1 point per [INT or TUI + APT] / 4",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 14,
    name: "Thaumaturgy",
    type: "Trade",
    formulaic: "+1 point per [INT or TUI + APT] / 4",
    desc: "None.",
    specStatus: 2,
  },
  {
    id: 15,
    name: "Weaponsmithing",
    type: "Trade",
    formulaic: "+1 point per [STR or END + APT] / 4",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 16,
    name: "Angling",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 17,
    name: "Botany",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 2,
  },
  {
    id: 18,
    name: "Butchery",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 19,
    name: "Cooking",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 20,
    name: "Mining",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 21,
    name: "Resourcefulness",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 2,
  },
  {
    id: 22,
    name: "Runereading",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 23,
    name: "Runic Inscription",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
  {
    id: 24,
    name: "Summoning",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 2,
  },
  {
    id: 25,
    name: "Triage",
    type: "Trade",
    formulaic: "+1 point per [APT] / 2",
    desc: "None.",
    specStatus: 0,
  },
];

export { skillExperienceCosts, skillCap, creatureAttributes, creatureSkills };
